version: '3.5'

services:
  mysql-timesoccer247:
    image: mysql:8.0.41-debian
    container_name: mysql-timesoccer247
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: timesoccer247
    volumes:
      - soccer_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    networks:
      - soccer_backend

  spring-timesoccer247:
    container_name: spring-timesoccer247
    image: lean2708/spring-timesoccer247:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - soccer_backend
    depends_on:
      - mysql

networks:
  soccer_backend:
    driver: bridge

volumes:
  soccer_data:
