server:
  servlet:
    context-path: /timesoccer247

spring:
  application:
    name: Spring_TimeSoccer247

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
# Database
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/timesoccer247}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


# Email
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
# JWT
jwt:
  signer-key: ${JWT_SIGNER_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
  reset-key: ${JWT_RESET_KEY}
  access-token:
    expiry-in-minutes: ${JWT_ACCESS_TOKEN_IN_MINUTES:15}
  refresh-token:
    expiry-in-days: ${JWT_REFRESH_TOKEN_IN_DAYS:20}
  reset:
    expiry-in-minutes: ${JWT_RESET_TOKEN_IN_MINUTES:15}

# Cloudinary
cloud:
  name: dz5wejuuf
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder-image: soccer247/image
  max-size-image: 10MB
  folder-video: soccer247/video
  max-size-video: 100MB

# VNPAY
payment:
  vnPay:
    url: ${VNPAY_URL}
    tmn-code: ${VNPAY_TMN_CODE}
    secret-key: ${VNPAY_SECRET_KEY}
    return-url: ${VNPAY_RETURN_URL}
    version: ${VNPAY_VERSION}
    command: ${VNPAY_COMMAND}
    order-type: ${VNPAY_ORDER_TYPE}

